// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TxnManualEntry2022.DbContexts;

#nullable disable

namespace TxnManualEntry2022.Migrations
{
    [DbContext(typeof(TmeDbContext))]
    partial class TmeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("TxnManualEntry2022.DTOs.AccountTxnDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FloorNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TxnAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TxnTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountTxns");
                });
#pragma warning restore 612, 618
        }
    }
}
