global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Data;
global using System.Diagnostics;
global using System.Globalization;
global using System.Linq;
global using System.Runtime.Serialization;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using Microsoft.EntityFrameworkCore; //todo: !!!NOT!!! System.Data.Entity;   ==> // The source IQueryable doesn't implement IDbAsyncEnumerable. Only sources that implement IDbAsyncEnumerable can be used for Entity Framework asynchronous operations. 
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
//global using Microsoft.Toolkit.Mvvm.ComponentModel;
//global using Microsoft.Toolkit.Mvvm.Input;
global using TxnManualEntry2022.Commands;
global using TxnManualEntry2022.DbContexts;
global using TxnManualEntry2022.DTOs;
global using TxnManualEntry2022.Exceptions;
global using TxnManualEntry2022.HostBuilders;
global using TxnManualEntry2022.Models;
global using TxnManualEntry2022.Service;
global using TxnManualEntry2022.Service.ReservationConflictValidators;
global using TxnManualEntry2022.Service.ReservationCreators;
global using TxnManualEntry2022.Stores;
global using TxnManualEntry2022.ViewModels;
global using static System.Diagnostics.Trace;

