// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Db.FinDemo.PowerTools.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Db.FinDemo.PowerTools.Models
{
    public partial class FinDemoContext
    {
        private IFinDemoContextProcedures _procedures;

        public virtual IFinDemoContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new FinDemoContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IFinDemoContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GroupedTxnResult>().HasNoKey().ToView(null);
        }
    }

    public partial class FinDemoContextProcedures : IFinDemoContextProcedures
    {
        private readonly FinDemoContext _context;

        public FinDemoContextProcedures(FinDemoContext context)
        {
            _context = context;
        }

        public virtual async Task<int> CreateAuditRecordAsync(string notes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "notes",
                    Size = -1,
                    Value = notes ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[CreateAuditRecord] @notes", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GroupedTxnResult>> GroupedTxnAsync(int? YearOfInt, int? MatchLen, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "YearOfInt",
                    Value = YearOfInt ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MatchLen",
                    Value = MatchLen ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GroupedTxnResult>("EXEC @returnValue = [dbo].[GroupedTxn] @YearOfInt, @MatchLen", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
