// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Db.FinDemo.PowerTools.Models
{
    public partial class GroupedTxnResult
    {
        public string TxDtl8 { get; set; }
        public int? Cnt { get; set; }
        public decimal? Min { get; set; }
        public decimal? Max { get; set; }
        public decimal? Avg { get; set; }
        public decimal? Sum { get; set; }
        public DateTime? FrstTxn { get; set; }
        public DateTime? LastTxn { get; set; }
    }
}
