// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Db.FinDemo.PowerTools.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Db.FinDemo.PowerTools.Models
{
    public partial interface IFinDemoContextProcedures
    {
        Task<int> CreateAuditRecordAsync(string notes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GroupedTxnResult>> GroupedTxnAsync(int? YearOfInt, int? MatchLen, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
