global using AmbienceLib;
global using Azure.Identity;
global using Azure.Security.KeyVault.Secrets;
global using Db.FinDemo7.Models;
global using MF.TxCategoryAssigner;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using StandardLib.Helpers;
global using System;
global using System.Windows;
global using System.Windows.Controls;
global using WpfUserControlLib.Helpers;
global using static AmbienceLib.SpeechSynth;
global using Application = System.Windows.Application;
